# Generated by Django 4.0.4 on 2022-05-13 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkedinapp', '0002_usertype_remove_useraccount_usertype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='usertype_id',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='usertype_name',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('company', 'Company')], max_length=9, null=True),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
