# Generated by Django 4.0.4 on 2022-05-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedinapp', '0004_rename_user_id_useraccount_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user',
            new_name='user_id',
        ),
    ]
